single stage

diff --git a/.github/workflows/deploy_tre_single_stage.yml b/.github/workflows/deploy_tre_single_stage.yml
--- a/.github/workflows/deploy_tre_single_stage.yml
+++ b/.github/workflows/deploy_tre_single_stage.yml
@@ -83,15 +83,15 @@ jobs:
         MGMT_STORAGE_ACCOUNT_NAME: ${{ secrets.MGMT_STORAGE_ACCOUNT_NAME }}
 
     - name: ACR Login
-        # failure in the first attempt indicates a new ACR, so we need to try again after it's been created
-        if: steps.ci_cache_cr_login.outcome != 'success'
-        run: |
-          # shellcheck disable=SC2034,SC2015,SC2125
-          for i in {1..3}; do
-            az acr login --name "${{ secrets.CI_CACHE_ACR_NAME }}" && ec=0 && break || ec=\$? && sleep 10
-          done
-          # shellcheck disable=SC2242
-          (exit \$ec)
+      # failure in the first attempt indicates a new ACR, so we need to try again after it's been created
+      if: steps.ci_cache_cr_login.outcome != 'success'
+      run: |
+        # shellcheck disable=SC2034,SC2015,SC2125
+        for i in {1..3}; do
+          az acr login --name "${{ secrets.CI_CACHE_ACR_NAME }}" && ec=0 && break || ec=\$? && sleep 10
+        done
+        # shellcheck disable=SC2242
+        (exit \$ec)
 
       - name: Start TRE
         uses: ./.github/actions/devcontainer_run_command
